### ISSUE TITLE
chrome disabled code page lol

### ISSUE THREAD

**Issue by JaxGamez** [Explodingstuff/WannaCry#1]
chrome just gave me a 'No' and I cannot download the virus to get revenge on my sister that deleted my Minecraft world

**Comment by SomeCodingCoolGuy** [comment]
?

**Comment by SomeCodingCoolGuy** [comment]
> chrome just gave me a 'No' and I cannot download the virus to get revenge on my sister that deleted my Minecraft world

Why do you want to do that?

**Comment by JaxGamez** [comment]
i was joking xD

**Comment by SomeCodingCoolGuy** [comment]
Whaaat.

**Comment by xzcollapse** [comment]
> i was joking xD

if you did want to do it, you could disable security in chrome settings or use git to download it
