### ISSUE TITLE
Part of githubs robots.txt

### ISSUE THREAD

**Issue by Artucuno** [Explodingstuff/WannaCry#2]
ooof https://github.com/robots.txt

**Comment by Andrew-Eathan** [comment]
lol it's an honor when you realise this guy is the only profile on the list

**Comment by mTvare6** [comment]
lol I too am from the same place, although I found this way back

**Comment by mTvare6** [comment]
but its also part of google malicious site list

**Comment by luis996** [comment]
I also ended here because robots.txt lol

**Comment by luis996** [comment]
quite late, through

**Comment by Project516** [comment]
> ooof https://github.com/robots.txt

Yeah saw that too - thought it was an Easter egg!
